### ISSUE TITLE
Difference between this buildpack and the one by tonycoco?

### ISSUE THREAD

**Issue by toreriklinnerud** [heroku/heroku-buildpack-ember-cli#11]
It would be helpful to know what the difference is between this buildpack and the one provided by https://github.com/tonycoco/heroku-buildpack-ember-cli.

**Comment by jmonster** [comment]
I've actually answered this question on another issue: https://github.com/heroku/heroku-buildpack-ember-cli/issues/5#issuecomment-179522842

> We actually attempted to use that buildpack ourselves; there's no sense putting effort into this if we didn't have to. Unfortunately it didn't play well with the rest of the Heroku ecosystem, such as [Pipelines](https://devcenter.heroku.com/articles/pipelines). I think we ran into some other issues getting our app deployed too but I can't recall the specifics at this moment. For what it's worth, I have successfully used that buildpack on personal projects in the past, so please don't take this as an insult to the tonycoco project :)

I'll leave this issue open for now in case anyone else comes along interested.

**Comment by toreriklinnerud** [comment]
Got it, thanks! I see that the heroku dashboard is causing the browser to make CORS preflight requests, is this something that you're hoping to tackle? The tonycoco buildpack solves this by letting you proxy requests. 

<img width="1272" alt="screen shot 2016-04-21 at 14 04 19" src="https://cloud.githubusercontent.com/assets/13226/14719443/3abf7324-07ca-11e6-9252-cfa14604bf19.png">

**Comment by jmonster** [comment]
You can actually do that already, if you like -- it's part of the static buildpack (that works in concert with this buildpack). You would just need to supply a config file that says where to proxy the requests. We write such a file out automatically, but use yours if it's provided.

**Comment by toreriklinnerud** [comment]
Ah, awesome, will check that out.
