### ISSUE TITLE
Force HTTPS?

### ISSUE THREAD

**Issue by jsquirrelz** [heroku/heroku-buildpack-ember-cli#13]
I'm new to Heroku so pardon my ignorance. Is there any additional configuration required to force a https redirect? I believe I'm using the current default [static.json](https://github.com/heroku/heroku-buildpack-ember-cli/blob/master/scripts/static.json) since I don't have one setup in our repo and have run `heroku config:set FORCE_HTTPS=true` in the command line. I've restarted via `heroku restart` and still not seeing a forced redirect. Am I missing something? Thank you.

**Comment by dmathieu** [comment]
Yes, this is provided by the static buildpack:
https://github.com/heroku/heroku-buildpack-static#https-only

**Comment by jsquirrelz** [comment]
closing in light of this not being the main repo (see [here](https://github.com/heroku/heroku-buildpack-emberjs/issues/8))
